version: "1"
services:
  - type: web
    name: search-api
    runtime: docker
    repo: https://github.com/Pratyay360/search-api
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
